### ISSUE TITLE
Dataset related problem

### ISSUE THREAD

**Issue by flying-rgb** [THUDM/Android-Lab#7]
Great work!
According to the paper, I found **Analysis** part at the first of each ROUND in Figure.7 Prompts of XML mode for Text-only Testing. 
But in the dataset released, l can't find and information about **Analysis** .
How to explain such difference?

**Comment by xuyifan-0731** [comment]
In Figure 7, the prompt we presented is used for testing closed-source (non-tunable) models. The dataset we provide is used for fine-tuning open-source models, where we only recorded the specific actions without adding any analysis and directly fine-tuned the model using only actions. This approach was chosen because we tested using GPT to supplement the analysis; however, we found that it did not improve the model's performance. If you are interested in the version with the added analysis data, please contact me via email. We apologize for not clarifying this point in our paper. Thank you for your suggestion, and we will include these details in the next version.
